### ISSUE TITLE
Issue during enum parsing

### ISSUE THREAD

**Issue by tigrankhachikyan** [postgraphql/postgraphql#540]
Just wander is this a bug or a real restriction?
```
Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "0_TO_50_000" does not.
    at assertValidName (/usr/lib/node_modules/postgraphql/node_modules/graphql/utilities/assertValidName.js:44:11)
    at /usr/lib/node_modules/postgraphql/node_modules/graphql/type/definition.js:632:42
    at Array.map (native)
    at defineEnumValues (/usr/lib/node_modules/postgraphql/node_modules/graphql/type/definition.js:631:21)
    at new GraphQLEnumType (/usr/lib/node_modules/postgraphql/node_modules/graphql/type/definition.js:549:20)
    at Object.enum (/usr/lib/node_modules/postgraphql/build/graphql/schema/type/getGqlOutputType.js:70:55)
    at callSwitchTypeCase (/usr/lib/node_modules/postgraphql/build/interface/type/switchType.js:19:43)
    at Object.switchType (/usr/lib/node_modules/postgraphql/build/interface/type/switchType.js:6:42)
    at createGqlOutputType (/usr/lib/node_modules/postgraphql/build/graphql/schema/type/getGqlOutputType.js:15:24)
    at /usr/lib/node_modules/postgraphql/build/graphql/utils/memoize.js:52:35
```

**Comment by benjie** [comment]
That error, according to the stack trace, is coming from graphql itself so it must be a real restriction. Would you be happy if we automatically prefixed it with underscore?

**Comment by tigrankhachikyan** [comment]
By auto prefixing `_`, at least we will pass this stage. 
So if you provide that fix, I'll be happy to test it.

**Comment by benjie** [comment]
Great. I'll try and put that in the v4 inflectors, track progress via #506
