### ISSUE TITLE
Best way to remove auto-generated queries and mutations in v4?

### ISSUE THREAD

**Issue by explicitcall** [postgraphql/postgraphql#558]
For some reason (which might be a feature, not a bug?) tables, which don't have any grants for a connection role, are still returned as part of the schema. But even with available grants, it's still useful to remove auto-generated queries for a schema, due to the way row level security is implemented in Postgres (e.g. RLS not available for views). I only want certain views be available to queries, but not tables that are used to form the view, which still requires select grants on those tables.

Here is what I've tried so far: 

```JavaScript
function RefinedSchema(builder) {
  builder.hook('GraphQLObjectType:fields',
  (fields, { extend, getTypeByName, graphql },
   { scope: { isRootMutation, isRootQuery }, fieldWithHooks }) => {
    if (isRootQuery) {
      fields.allForbiddenThings = undefined;
    }
    
    return fields;
  });
}
```

The result:

```
Error: Schema query must be Object Type but got: undefined.
    at invariant (/Volumes/Data/project/services/frontend/node_modules/graphql/jsutils/invariant.js:19:11)
    at new GraphQLSchema (/Volumes/Data/project/services/frontend/node_modules/graphql/type/schema.js:72:88)
    at Object.newWithHooks (/Volumes/Data/RavenPostSails/services/frontend/node_modules/graphile-build/node8plus/makeNewBuild.js:389:20)
    at SchemaBuilder.buildSchema (/Volumes/Data/project/services/frontend/node_modules/graphile-build/node8plus/SchemaBuilder.js:190:37)
    at Object.exports.createPostGraphQLSchema (/Volumes/Data/project/services/frontend/node_modules/postgraphile-core/node8plus/index.js:60:18)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by benjie** [comment]
Try switching:

```js
      fields.allForbiddenThings = undefined;
```

for

```js
      delete fields.allForbiddenThings;
```
?

Though personally I'd prefer an immutable approach, such as:

```js
if (isRootQuery) {
  const {allForbiddenThings, ...rest} = fields;
  return rest;
}
return fields;
```
(Probbably requires Babel stage 2 or 3)

**Comment by explicitcall** [comment]
Thanks, I didn't expect `delete` and `= undefined` to behave differently, especially after reading that Node.js recommends using the latter instead of the former for performance reasons as described in https://medium.com/the-node-js-collection/get-ready-a-new-v8-is-coming-node-js-performance-is-changing-46a63d6da4de

**Comment by benjie** [comment]
Yeah, I guess `graphql` are looping based on `Object.keys()` or similar.
