### ISSUE TITLE
set uuid column to null

### ISSUE THREAD

**Issue by trabur** [postgraphql/postgraphql#621]
I'm submitting a ... 
- [ ] bug report
- [ ] feature request
- [x] question 

PostGraphQL version:
3.5.0

Is it possible to set a "Uuid" column to null? When I try to set the value to null I get, "Variable \"$primaryAddressId\" got invalid value null.\nExpected \"Uuid!\", found null."...

```
mutation Update($id: Uuid!, $primaryAddressId: Uuid!) {
  updateCustomerById(input: {
    id: $id,
    clientMutationId: "123",
    customerPatch: {
      id: $id,
      primaryAddressId: $primaryAddressId
    }
  }) {
    customer {
      id
    }
  }
}
```

Variables
```
{
  "id": "00488484-a0a3-434d-952b-300935460f82",
  "primaryAddressId": null
}
```

Result:
```
{
  "errors": [
    {
      "message": "Variable \"$primaryAddressId\" got invalid value null.\nExpected \"Uuid!\", found null.",
      "locations": [
        {
          "line": 1,
          "column": 29
        }
      ],
      "stack": "GraphQLError\n    at getVariableValues (/Users/doorway/Projects/fleetgrid/backend/node_modules/graphql/execution/values.js:78:15)\n    at buildExecutionContext (/Users/doorway/Projects/fleetgrid/backend/node_modules/graphql/execution/execute.js:186:54)\n    at Object.execute (/Users/doorway/Projects/fleetgrid/backend/node_modules/graphql/execution/execute.js:109:17)\n    at /Users/doorway/Projects/fleetgrid/backend/node_modules/postgraphql/src/postgraphql/http/createPostGraphQLHttpRequestHandler.js:407:16\n    at /Users/doorway/Projects/fleetgrid/backend/node_modules/postgraphql/src/postgraphql/withPostGraphQLContext.ts:74:18\n    at step (/Users/doorway/Projects/fleetgrid/backend/node_modules/tslib/tslib.js:122:27)\n    at Object.next (/Users/doorway/Projects/fleetgrid/backend/node_modules/tslib/tslib.js:103:57)\n    at fulfilled (/Users/doorway/Projects/fleetgrid/backend/node_modules/tslib/tslib.js:93:62)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:208:7)"
    }
  ]
}
```

It seams like my only option is to set it to "00000000-0000-0000-0000-000000000000" then run flags in my application to account for this.

**Comment by benjie** [comment]
Your query explicitly states that the variable `$primaryAddressId` must be a non-null Uuid:

```
mutation Update($id: Uuid!, $primaryAddressId: Uuid!) {
```

If you remove that `!` then the query will accept a null Uuid (assuming the variable is only used where a nullable ID is valid).

**Comment by benjie** [comment]
[semi-automated message] To keep things manageable I'm going to close this issue as I think it's solved; but if not or you require further help please re-open it.
