### ISSUE TITLE
"Cannot read property 'get' of null" in mutation

### ISSUE THREAD

**Issue by enisdenjo** [postgraphql/postgraphql#628]
I am facing a problem upon calling a **mutation**. It is specific to this exact mutation, all other mutations work as expected.

PostGraphQL version: 3.5.0

The table structures:
```sql
public.document (
    id         uuid PRIMARY KEY,
    x_id       uuid NOT NULL REFERENCES public.x(id),
    ...rest
)
public.x (
    id         uuid PRIMARY KEY,
    ...rest
)
```

The SQL function:
``` sql
CREATE OR REPLACE FUNCTION public.update_x_id_for_document(
    document_id uuid,
    x_id uuid
) RETURNS public.document AS
$$
    UPDATE public.document
        SET x_id = update_x_id_for_document.x_id
    WHERE (id = update_x_id_for_document.document_id)
    RETURNING *
$$
LANGUAGE SQL VOLATILE;
```

then I run the mutation through GraphQL:
```
mutation UpdateXIdForDocument(
  $documentId:Uuid!
  $xId:Uuid!
) {
  updateXIdForDocument(input: {
    documentId:$documentId,
    xId:$xId,
  }) {
    document {
      id
    }
    xByXId {
      id
    }
  }
}
```
with **variables** set correctly.

The response looks like this:
```json
{
  "data": {
    "updateXIdForDocument": {
      "document": null,
      "xByXId": null
    }
  },
  "errors": [
    {
      "message": "Cannot read property 'get' of null",
      "locations": [{ "line": 11, "column": 3 }],
      "path": [
        "updateXIdForDocument",
        "xByXId"
      ],
      "stack":
        "TypeError: Cannot read property 'get' of null\n    at /path/to/node_modules/postgraphql/build/postgres/inventory/collection/PgRelation.js:31:61\n    at Array.reduce (<anonymous>)\n    at PgRelation.getHeadKeyFromTailValue (/path/to/node_modules/postgraphql/build/postgres/inventory/collection/PgRelation.js:30:37)\n    at Object.<anonymous> (/path/to/node_modules/postgraphql/build/graphql/schema/collection/createCollectionRelationTailGqlFieldEntries.js:43:52)\n    at step (/path/to/node_modules/tslib/tslib.js:121:27)\n    at Object.next (/path/to/node_modules/tslib/tslib.js:102:57)\n    at /path/to/node_modules/tslib/tslib.js:95:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/path/to/node_modules/tslib/tslib.js:91:16)\n    at Object.resolve (/path/to/node_modules/postgraphql/build/graphql/schema/collection/createCollectionRelationTailGqlFieldEntries.js:37:36)"
    }
  ]
}

```

Besides the error in data retrieval, the document row is also not updated...

All the relations are set up correctly and running the raw SQL function through psql correctly mutates the document table.

I truly don't know how to exactly reproduce this bug because it appeared suddenly, all other functions follow the same coding principles as the function above, so this specific function above does not deviate from anything in my codebase. It just does not work.

Any ideas?

Thanks in advance!
Denis

**EDIT:**

Okay so I've figured it out. It is because of **ROW LEVEL SECURITY**, the public.document table has the following policy:

```sql
ALTER TABLE public.document ENABLE ROW LEVEL SECURITY;

CREATE POLICY select_document ON public.document FOR SELECT
    USING (
        (
            company_id = (
                SELECT company_id FROM public.user WHERE ('*JWT token logic here*')
            )
        )
    );
```

As soon as I removed the ROW LEVEL SECURITY everything started working as expected.

**EDIT 2:**

After creating a policy for UPDATE everything is back to normal.

Sorry for the unrelated issue post ☹️

**Comment by benjie** [comment]
Thanks for sharing - this will help others who face similar issues and google it.
