### ISSUE TITLE
TypeError: Cannot read property 'tableType' of undefined

### ISSUE THREAD

**Issue by disarticulate** [postgraphql/postgraphql#636]
I'm submitting a ... 
- [x ] bug report
- [ ] feature request
- [ ] question 

PostGraphQL version:

4.0.0-alpha2.9

Minimal SQL file that can be loaded into a clean database:
```

```

Steps to reproduce:

Current behavior: 
```
graphql_1   | TypeError: Cannot read property 'tableType' of undefined
graphql_1   |     at introspectionResultsByKind.class.forEach.table (/usr/local/lib/node_modules/postgraphql/node_modules/graphile-build-pg/node8plus/plugins/PgTablesPlugin.js:64:40)
graphql_1   |     at Array.forEach (<anonymous>)
graphql_1   |     at PgTablesPlugin.builder.hook (/usr/local/lib/node_modules/postgraphql/node_modules/graphile-build-pg/node8plus/plugins/PgTablesPlugin.js:42:38)
graphql_1   |     at SchemaBuilder.applyHooks (/usr/local/lib/node_modules/postgraphql/node_modules/graphile-build/node8plus/SchemaBuilder.js:149:20)
graphql_1   |     at SchemaBuilder.createBuild (/usr/local/lib/node_modules/postgraphql/node_modules/graphile-build/node8plus/SchemaBuilder.js:183:10)
graphql_1   |     at SchemaBuilder.buildSchema (/usr/local/lib/node_modules/postgraphql/node_modules/graphile-build/node8plus/SchemaBuilder.js:189:26)
graphql_1   |     at Object.exports.createPostGraphQLSchema (/usr/local/lib/node_modules/postgraphql/node_modules/postgraphile-core/node8plus/index.js:60:18)
graphql_1   |     at <anonymous>
graphql_1   |     at process._tickCallback (internal/process/next_tick.js:188:7)
```
Expected behavior:
Introspected database

I loaded a postgres database w/postgis using a standard ubuntu tool
```
osm2pgsql -a -d osm -U $POSTGRES_USER --slim $FILE
```

**Comment by benjie** [comment]
PostGraphQL v4 is in alpha; you're using a very old version that had quite a few issues. Please update to the latest version (`postgraphql@next` or `4.0.0-alpha2.22`) and then let me know if the issue still exists.

**Comment by disarticulate** [comment]
I went to the latest releases and downloaded. I'll try postgraphql@next

**Comment by benjie** [comment]
Oops; seems I've not been pushing those tags! Pushed the latest tags now; the branch is `benjie/graphql-build` (for legacy reasons) and you can track progress via #506

**Comment by disarticulate** [comment]
Thanks. I got it up and running in a minimal docker:
```
FROM node:9-alpine

RUN mkdir /app

WORKDIR /app

RUN npm install -g postgraphql@next

COPY ./.graphql/entrypoint /app/entrypoint

EXPOSE 5000

ENTRYPOINT /app/entrypoint
```

**Comment by benjie** [comment]
[semi-automated message] To keep things manageable I'm going to close this issue as I think it's solved; but if not or you require further help please re-open it.
